### ISSUE TITLE
How to get this physical address

### ISSUE THREAD

**Issue by yym-tiger** [jbech-linaro/trasher#1]
hello
How to get this physical address, can not find in.params structure
Looking forward to your reply. thanks.

**Comment by jockebech** [comment]
Hi @yym-hjr ,

Here is an updated answer, with correct and verified information, please forget what I said earlier today. The easiest way to get the correct physical address for param[0] is (apply this patch to the kernel branch we are using in OP-TEE).

```patch
diff --git a/drivers/tee/optee/call.c b/drivers/tee/optee/call.c
index f7b7b404c990..2e3a29a0adde 100644
--- a/drivers/tee/optee/call.c
+++ b/drivers/tee/optee/call.c
@@ -341,6 +341,8 @@ int optee_invoke_func(struct tee_context *ctx, struct tee_ioctl_invoke_arg *arg,
 	if (rc)
 		goto out;
 
+	printk(KERN_ERR "Param phys: 0x%08x\n", (u32)msg_arg->params->u.tmem.buf_ptr);
+
 	if (optee_do_call_with_arg(ctx, msg_parg)) {
 		msg_arg->ret = TEEC_ERROR_COMMUNICATION;
 		msg_arg->ret_origin = TEEC_ORIGIN_COMMS;
```

Boot up the device, and run `trasher` in the console in QEMU, you should see a print saying something like this:
```
Param phys: 0x81f01000
```

After that update [this file and line](https://github.com/jbech-linaro/trasher/blob/master/host/main.c#L25)  (i.e, `READ_ADDR` with the value you just found from the print). Then rebuild everything and run trasher again, this time it shall work as intended. On my computer running everything latest as of today I get this.

```bash
Please press Enter to activate this console. 
root@Vexpress:/ trasher 
NW: Thread with 0x76e2c470 created
NW: offset: 0x00000000, page_addr: 0x81f01000
NW: Try to map and read the data from: 0x81f01000
1. NW: Invoke the TA with initial buf value: 0xDEADBABE
Param phys: 0x81f01000
2. NW: Waiting for secure side / TA to update the buffer without returning back to NW
3. NW: Found updated TEE shared memory: 0xBAADF00D
4. NW: Sleep 3 seconds ...
5. NW: Write new value to shared memory: 0xCAFEBABE (TA finds this and return back to NW)
root@Vexpress:/
```

I hope this helps.

**Comment by jbech-linaro** [comment]
I realised I got the pointers wrong, I think the correct param should be:
```patch
diff --git a/drivers/tee/optee/call.c b/drivers/tee/optee/call.c
index f7b7b404c990..27f18da3413f 100644
--- a/drivers/tee/optee/call.c
+++ b/drivers/tee/optee/call.c
@@ -21,6 +21,7 @@
 #include <linux/uaccess.h>
 #include "optee_private.h"
 #include "optee_smc.h"
+#include "../tee_private.h"
 
 struct optee_call_waiter {
 	struct list_head list_node;
@@ -341,6 +342,7 @@ int optee_invoke_func(struct tee_context *ctx, struct tee_ioctl_invoke_arg *arg,
 	if (rc)
 		goto out;
 
+	printk(KERN_ERR "Param PA: 0x%08x\n", (u32)((struct optee_msg_arg *)shm->paddr)->params);
 	if (optee_do_call_with_arg(ctx, msg_parg)) {
 		msg_arg->ret = TEEC_ERROR_COMMUNICATION;
 		msg_arg->ret_origin = TEEC_ORIGIN_COMMS;
```
And that indeed seems static, having that said I haven't tested this yet. I'll give it a try later on.

**Comment by jockebech** [comment]
@yym-hjr , I've updated my previous answer, everything works as expected if you follow my answer.

**Comment by yym-hjr** [comment]
Thank you very much for your answer. Thank you for helping me solve this problem

**Comment by yym-tiger** [comment]
Hello, I have a new question about shared memory. When the first TEEC_InvokeCommand allocates a shared memory, and the assignment, when the second TEEC_InvokeCommand, does not pass any arguments,  but can not read and write the shared memory. The error log is as follows:
NW: TEEC_InvokeCommand failed with code 0xffff3024 origin 0x3
```c


// linux code: 
`TEEC_SharedMemory shm;
	shm.buffer = s1;
	shm.flags = TEEC_MEM_INPUT | TEEC_MEM_OUTPUT;
	shm.size  = 12;
	res = TEEC_RegisterSharedMemory(&ctx, &shm);
	check_res(res, "TEEC_RegisterSharedMemory");
	memset(&op, 0, sizeof(op));
	op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_WHOLE ,TEEC_NONE,TEEC_NONE,TEEC_NONE);
	
	op.params[0].memref.parent= &shm;
	op.params[0].memref.offset = 0;
	op.params[0].memref.size = count;
	
	res = TEEC_OpenSession(&ctx, &sess, &uuid,
			       	TEEC_LOGIN_PUBLIC, NULL, NULL, &err_origin);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_Opensession failed with code 0x%x origin 0x%x",res, err_origin);

// the first  TEEC_InvokeCommand
	res = TEEC_InvokeCommand(&sess, MEMARY_NO_1, &op,&err_origin);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_InvokeCommand failed with code 0x%x origin 0x%x",res, err_origin);
	
//the second TEEC_InvokeCommand
	res = TEEC_InvokeCommand(&sess, MEMARY_NO_2,NULL, &err_origin);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_InvokeCommand failed with code 0x%x origin 0x%x",res, err_origin);`


// ta code
`static TEE_Result memory_first(uint32_t param_types,TEE_Param params[4])
{
	uint8_t *p;
	int32_t in_len;
	uint32_t exp_param_types = TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INOUT,
						   TEE_PARAM_TYPE_NONE,
						   TEE_PARAM_TYPE_NONE,
						   TEE_PARAM_TYPE_NONE);

	if (param_types != exp_param_types)
		return TEE_ERROR_BAD_PARAMETERS;
	
	p = params[0].memref.buffer;
	in_len = params[0].memref.size;
	TEE_SetInstanceData(p);	
	IMSG ("size=%d     optee_string=%s", in_len, p);
	return TEE_SUCCESS;
}

static TEE_Result memory_second(void)
{
	IMSG ("optee_string_second=%s", (char *)TEE_GetInstanceData());	
	return TEE_SUCCESS;
}`

```

**Comment by jockebech** [comment]
The error code is:
```c
lib/libutee/include/tee_api_defines.h:#define TEE_ERROR_TARGET_DEAD             0xFFFF3024
```
So most likely the TA has crashed / panic'd for some reason. Fire up GDB ([instructions](https://github.com/OP-TEE/build/blob/master/docs/debug.md)) and check what is happening around:
```bash
$ git grep -n TEE_ERROR_TARGET_DEAD
core/arch/arm/kernel/abort.c:298:       ai->regs->r0 = TEE_ERROR_TARGET_DEAD;
core/arch/arm/kernel/abort.c:324:       ai->regs->x0 = TEE_ERROR_TARGET_DEAD;
core/arch/arm/kernel/user_ta.c:590:             res = TEE_ERROR_TARGET_DEAD;
core/arch/arm/tee/arch_svc_a32.S:119:   ldr     r0, =TEE_ERROR_TARGET_DEAD
core/arch/arm/tee/arch_svc_a64.S:202:   ldr     w0, =TEE_ERROR_TARGET_DEAD
core/kernel/tee_ta_manager.c:546:               return TEE_ERROR_TARGET_DEAD;
core/kernel/tee_ta_manager.c:601:               return TEE_ERROR_TARGET_DEAD;
core/kernel/tee_ta_manager.c:611:               res = TEE_ERROR_TARGET_DEAD;
lib/libutee/include/tee_api_defines.h:64:#define TEE_ERROR_TARGET_DEAD             0xFFFF3024
lib/libutee/tee_api.c:161:          res != TEE_ERROR_TARGET_DEAD)
```
I suspect that `p` could be the culprit here, i.e, the one you are using to `TEE_Set/GetInstanceData`. A quick thing to test would be to just comment out those from the code.

Btw, what is the intention with your work? The reason for asking is that I want to make sure that you are not trying to use this way of "sharing" memory between secure and non-secure world. My `trasher` TA was  just created to show that it's indeed possible to touch (shared) memory both from secure and non-secure world at the same time. I.e, this is kind of "hacking/abusing" the system. The correct way is to allocate shared memory and then pass the data back and forth between the client and the TA itself using the functions described by the GP Client API.

**Comment by yym-tiger** [comment]
@jbech-linaro 
Hello, thank you very much for your reply
Whether it is shared memory, or your trasher TA method, to achieve the effect is consistent. The reason I do this is when I second TEEC_InvokeCommand when I do not pass any parameters. In the linux side and optee side, can both read and write to my first shared memory. Looks like your trasher Ta does not seem to reach what I want.
@Etienne-lms   said it seems right, he said
TEE_Set/GetInstanceData() can only be used to refer to memory that is owned by the TA: in the TA heap (malloc pool), in the TA static read-only or read/write data, or in the TA stack but this later is obviously NOT recommended.

A shared memory buffer provided to a TA as an invocation parameters is not memory owned by the TA. Such a shared memory can be accessed by the TA only for the very specific invocation(s) that referred the buffer as an argument. If a TA needs to access a shared memory area for several invocations, the client must invoke the TA each time with the buffer passed as parameter. And note that even so, the buffer may change of (virtual) address at each TA invocation, hence TA must get the buffer address from the invocation parameters and cannot assume it always located at the same (virtual) address.

OP-TEE currently provides no support for allocating/assigning a shared memory buffer that is mapped/accessible in the TA address space for the whole TA life cycle.

**Comment by jockebech** [comment]
> TEE_Set/GetInstanceData() can only be used to refer to memory that is owned by the TA: in the TA heap (malloc pool), in the TA static read-only or read/write data, or in the TA stack but this later is obviously NOT recommended.

Right, that was basically what I had in mind in my previous reply, when I mentioned the Get/Set functions.

So, now I'm with you what you are trying to do, but wouldn't it work to allocated memory (with TEE_Malloc) and use that (copy in data from shm to the newly allocated memory)? Or you need lots of memory?

**Comment by yym-tiger** [comment]
@jbech-linaro
Hello, thank you very much for your reply. Can not be reallocated by TEE_Malloc or TEE_CreatePersistentObject. This efficiency will be too low.I want to do is for the first time TEEC_InvokeCommand assigns a shared memory, the second TEEC_InvokeCommand does not pass any parameters (or do not pass the first TEEC_InvokeCommand related parameters) Able to read and write this shared memory.

**Comment by jockebech** [comment]
Alright, seems like you've identified a use case which isn't fully supported by OP-TEE as of today.

**Comment by yym-tiger** [comment]
Thank you for your reply
